### ISSUE TITLE
The annotation of the labels. 

### ISSUE THREAD

**Issue by NimoXW** [DIAGNijmegen/panorama_labels#1]
The labels are assigned as follows:
                          labels={'Background':	0,
                            'PDAC lesion':	1,
                            'Veins':	2,
                            'Arteries':	3,
                            'Pancreas parenchyma':	4,
                            'Pancreatic duct':	5,
                            'Common bile duct':	6
                          },
But, I've encountered a potential issue with the labeling in your dataset.  I got this error when build the dataset for training the nnUNet. Is there any labels wrong?  
100244_00001.nii.gz.
Expected: [0, 1, 2, 3, 4, 5, 6]
Found: [0. 1. 2. 3. 4. 5. 6. 8.]

Thank you for your assistance and support!

**Comment by HongkunSun** [comment]
101994_00001.nii.gz 和101687_00001.nii.gz 有相同的问题。并且，100244_00001.nii.gz虽然有classes 8，但是，使用3d slicer 查看不到关于classes 8的目标区域。

**Comment by Luffy03** [comment]
Hi, I found class 7. Is it normal?

**Comment by HongkunSun** [comment]
> Hi, I found class 7. Is it normal?

yes，I also found.

**Comment by alexandreroutier** [comment]
Hello,

I notice that this has been solved in bd5f666 on June 21st by @NataliaAlves13. I believe we can close this issue.

Best,
Alexandre

**Comment by NataliaAlves13** [comment]
That is correct, I'll close the issue now.
