### ISSUE TITLE
Empty label: 100051_00001.nii.gz

### ISSUE THREAD

**Issue by byhwhite** [DIAGNijmegen/panorama_labels#2]
Label file [100051_00001.nii.gz] seems like an empty file?

**Comment by alexandreroutier** [comment]
Hello,

I have cloned the repo on my side and noticed the same thing:

```text
panorama_labels/automatic_labels ❯ du -sh * | sort -h | head
0       100051_00001.nii.gz
84K     100036_00001.nii.gz
92K     101460_00001.nii.gz
92K     101556_00001.nii.gz
96K     100108_00001.nii.gz
96K     100802_00001.nii.gz
96K     101433_00001.nii.gz
100K    100282_00001.nii.gz
100K    101443_00001.nii.gz
104K    100286_00001.nii.gz


panorama_labels/manual_labels ❯ du -sh * | sort -h | head
28K     101129_00001.nii.gz
32K     100403_00001.nii.gz
36K     101576_00001.nii.gz
36K     101592_00001.nii.gz
40K     100226_00001.nii.gz
48K     101139_00001.nii.gz
48K     101969_00001.nii.gz
52K     100583_00001.nii.gz
52K     101342_00001.nii.gz
56K     100056_00001.nii.gz
```

However, `100051_00001.nii.gz` seems to be the only empty file on the repository. Since `clinical_information.xlsx` indicates that this patient is non-PDAC, it should be safe to generate an empty mask instead.

**Comment by NataliaAlves13** [comment]
The label for case 100051 has now been updated in the repository.
Thank you for bringing up this issue.
Please let me know if you have any further questions.
